import { Providers } from "@/redux/provider";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

const Navbar = dynamic(() => import("@/components/Navbar"), { ssr: false });

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import dynamic from "next/dynamic";
import HomeLayout from "@/components/layouts/HomeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Expenso - Track your expenses online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <HomeLayout>{children}</HomeLayout>
          <div id="modal"></div>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
